apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: nginx-ingress-lb
  name: nginx-ingress-lb
  namespace: kube-system
spec:
  replicas: 1
  template:
    spec:
      $setElementOrder/containers:
      - name: nginx-ingress-lb
      containers:
      - name: nginx-ingress-lb
        resources:
          limits:
            memory: 100Mi
          requests:
            memory: 100Mi
